# Smokescreen testing that it can be installed via cargo and runs.
name: Cargo install

on:
  push:
    branches: [master, dev]
    tags: ["v*.*.*"]
  pull_request:
    types: [review_requested, ready_for_review]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  install:
    name: "Smokescreen Install"
    runs-on: self-hosted

    steps:
      - name: Cargo install
        run: cargo install --git ${{ github.server_url }}/${{ github.repository }} swc swc_web --rev $GITHUB_SHA
      
      - name: CLI works
        run: swc --version && swc --help

      - name: Web works
        run: swc-web --version && swc-web --help
