name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    types: [review_requested, ready_for_review]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  basic:
    name: "Rust"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Format
        run: cargo +nightly fmt --all -- --check

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: --release --all-targets --all-features

      - name: Style
        run: |
          cargo clippy --release --all-targets --all-features -- -D warnings || true

      - uses: actions-rs/cargo@v1
        name: Documentation
        with:
          command: doc
          args: --release --no-deps --all-features

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Build (Tests)
        with:
          command: test
          args: --no-run --release --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --release --all-targets # no --all-features

  polkadot_version_locked:
    name: "Polkadot (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Checkout Polkadot
        run: |
          mkdir -p repos/polkadot
          cd repos/polkadot
          git init
          git remote add origin https://github.com/paritytech/polkadot
          git fetch origin 190515004445a60a54711547765baf7e5bcb5e6d
          git fetch origin refs/tags/v0.9.19:refs/tags/v0.9.19
          git fetch origin refs/tags/v0.9.20:refs/tags/v0.9.20
          git checkout 190515004445a60a54711547765baf7e5bcb5e6d

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,polkadot "polkadot::"
  
  polkadot_master:
    name: "Polkadot (master)"
    needs: polkadot_version_locked
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Checkout Polkadot
        run: |
          mkdir -p repos/polkadot
          cd repos/polkadot
          git init
          git remote add origin https://github.com/paritytech/polkadot
          git fetch origin master
          git fetch origin refs/tags/v0.9.19:refs/tags/v0.9.19
          git fetch origin refs/tags/v0.9.20:refs/tags/v0.9.20
          git checkout master

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (master)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,polkadot "polkadot::"

  moonbeam_version_locked:
    name: "Moonbeam (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Checkout Moonbeam
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: PureStake/moonbeam
          path: repos/moonbeam
          ref: 9665bd46a19ef4cc4ad1327f360150d7743dfd76

      - uses: actions-rs/cargo@v1
        name: Moonbeam Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,moonbeam "moonbeam::"

  composable_version_locked:
      name: "ComposableFI (version locked)"
      needs: basic
      runs-on: self-hosted

      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly

        - name: Checkout ComposableFI
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
            repository: ComposableFi/composable
            path: repos/composable
            ref: b3492f26dd4fde7aca272bae8460682babbdbdd3

        - uses: actions-rs/cargo@v1
          name: ComposableFI Tests (version locked)
          with:
            command: test
            args: --release --all-targets --features version-locked-tests,composable "composable::"
