name: CI

on:
  push:
    branches: [master, dev]
    tags: ["v*.*.*"]
  pull_request:
    types: [review_requested, ready_for_review]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  basic:
    name: "Rust"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2

      - name: Rust Version Info
        run: |
          cargo version
          rustc --version
          cargo clippy --version

      - name: Format
        run: cargo +nightly fmt --all -- --check

      #- uses: actions-rs/cargo@v1
      #  name: Check
      #  with:
      #    command: check
      #    args: --locked --release --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --locked --release --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Build (Tests)
        with:
          command: test
          args: --locked --no-run --release --all-targets

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --locked --release --all-targets --all-features -- -D warnings

      - uses: actions-rs/cargo@v1
        name: Documentation
        with:
          command: doc
          args: --locked --release --no-deps --all-features

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --locked --release --all-targets # no --all-features

      - uses: actions-rs/cargo@v1
        name: Doc Test
        with:
          command: test
          args: --locked --release --doc

  polkadot_version_locked:
    name: "Polkadot (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Checkout Polkadot
        run: |
          mkdir -p repos/polkadot
          cd repos/polkadot
          git init
          git remote add origin https://github.com/paritytech/polkadot
          git fetch origin 4863d0a33a4a3534236f76abb5b1dc91751c6c34
          git fetch origin refs/tags/v0.9.19:refs/tags/v0.9.19
          git fetch origin refs/tags/v0.9.20:refs/tags/v0.9.20
          git checkout 4863d0a33a4a3534236f76abb5b1dc91751c6c34

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,polkadot "polkadot::"

  polkadot_master:
    name: "Polkadot (master)"
    needs: polkadot_version_locked
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2

      - name: Checkout Polkadot
        run: |
          mkdir -p repos/polkadot
          cd repos/polkadot
          git init
          git remote add origin https://github.com/paritytech/polkadot
          git fetch origin master
          git fetch origin refs/tags/v0.9.19:refs/tags/v0.9.19
          git fetch origin refs/tags/v0.9.20:refs/tags/v0.9.20
          git checkout master

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (master)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,polkadot "polkadot::"

  substrate_version_locked:
    name: "Substrate (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2

      - name: Checkout Substrate
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: paritytech/substrate
          path: repos/substrate
          ref: 1fd71c7845d6c28c532795ec79106d959dd1fe30

      - uses: actions-rs/cargo@v1
        name: Substrate Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,substrate "substrate::"

  cumulus_version_locked:
    name: "Cumulus (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Checkout Cumulus
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: paritytech/cumulus
          path: repos/cumulus
          ref: 530a0aaf0c8a422f708415873d1366ae4c8ea456

      - uses: actions-rs/cargo@v1
        name: Cumulus Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,cumulus "cumulus::"

  acala_version_locked:
    name: "Acala (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Checkout Acala
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: AcalaNetwork/Acala
          path: repos/acala
          ref: c64bb09242bbb8db46ff64a97f30331a3006875e

      - uses: actions-rs/cargo@v1
        name: Acala Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,acala "acala::"

  moonbeam_version_locked:
    name: "Moonbeam (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Checkout Moonbeam
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: PureStake/moonbeam
          path: repos/moonbeam
          ref: 54e40e2aa3f1f41a45a7df067a6ac6a0256cda6a

      - uses: actions-rs/cargo@v1
        name: Moonbeam Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,moonbeam "moonbeam::"

  composable_version_locked:
    name: "ComposableFI (version locked)"
    needs: basic
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Checkout ComposableFI
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: ComposableFi/composable
          path: repos/composable
          ref: 6f407847041ea170db8ddfb4770e0492e253db1f

      - uses: actions-rs/cargo@v1
        name: ComposableFI Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,composable "composable::"
