name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: "Rust"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache
        with:
          cache-on-failure: true

      - name: Format
        run: cargo +nightly fmt --all -- --check

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Style
        with:
          command: clippy
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Documentation
        with:
          command: doc
          args: --no-deps --all-features

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Build (Tests)
        with:
          command: test
          args: --no-run --release --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Static Tests
        with:
          command: test
          args: --release --all-targets

  substrate_version_locked:
    name: "Substrate (version locked)"
    needs: rust
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache
        with:
          cache-on-failure: true

      - name: Checkout Substrate
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: paritytech/substrate
          path: repos/substrate
          ref: 06d43cba9c2498d058a600dfe200c75e36d1181f

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,substrate-tests

  polkadot_version_locked:
    name: "Polkadot (version locked)"
    needs: rust
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache
        with:
          cache-on-failure: true

      - name: Checkout Polkadot
        run: |
          mkdir -p repos/substrate
          cd repos/substrate
          git init
          git remote add origin https://github.com/paritytech/substrate
          git fetch origin master
          gc master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: paritytech/polkadot
          path: repos/polkadot
          # CHANGE HERE and in `polkadot_parse.rs``.
          ref: 190515004445a60a54711547765baf7e5bcb5e6d

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (version locked)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,polkadot-tests
  
  polkadot_master:
    name: "Polkadot (master)"
    needs: polkadot_version_locked
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache
        with:
          cache-on-failure: true

      - name: Checkout Polkadot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: paritytech/polkadot
          path: repos/polkadot
          ref: master

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (master)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests,polkadot-tests
