name: Markdown

on:
  push:
    branches: [master, dev]
  pull_request:
    types: [review_requested, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Link Markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/mlc_config.json'
          use-quiet-mode: "yes"
