name: Polkadot master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  polkadot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache
        with:
          cache-on-failure: true

      - name: Checkout Polkadot (master)
        uses: actions/checkout@v3
        with:
          repository: paritytech/polkadot
          path: repos/polkadot
          ref: master

      - uses: actions-rs/cargo@v1
        name: Polkadot Tests (master)
        with:
          command: test
          args: --release --all-targets --features version-locked-tests
