name: Rust

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: -q --all-targets --all-features

      - name: Format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Documentation
        with:
          command: doc
          args: -q --no-deps --all-features

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: -q --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Style
        with:
          command: clippy
          args: -q --all-features

      - uses: actions-rs/cargo@v1
        name: Tests
        with:
          command: test
          args: --release --all-targets --all-features
