name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: buildjet-4vcpu-ubuntu-2004
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        name: Rust Cache
        with:
          cache-on-failure: true

      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Style
        with:
          command: clippy
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Documentation
        with:
          command: doc
          args: --no-deps --all-features

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Build (Tests)
        with:
          command: test
          args: --no-run --release --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: Static Tests
        with:
          command: test
          args: --release --all-targets
